spring:
    profiles:
        active: dev
    datasource:
        driver-class-name: com.mysql.jdbc.Driver
        url: jdbc:mysql://127.0.0.1:3306/springboot?useSSL=false&serverTimezone=UTC&useUnicode=true&characterEncoding=utf8&characterSetResults=utf8&autoReconnect=true
        username: root
        password: 123456
    jpa:
        hibernate:
            ddl-auto: update
        show-sql: true